apps/twitter/urls.py
# coding=utf-8
from django.conf.urls import patterns, include, url

urlpatterns = patterns('twitter.views',
	
	#url('^mis_seguimientos/$', 'mis_seguimientos', name='social-mis-contactos'),
	url(r'^perfil_social/(?P<username>([^/]+))/$', 'ver_perfil_social', name="social-perfil"),
	url('^seguir/$', 'seguir', name='social-seguir'),
	url('^escribir/$', 'escribir', name='social-escribir'),
	url('^reescribir/(?P<mensaje_id>\d+)/$', 'reescribir', name='social-reescribir'),
	url('^responder/(?P<mensaje_id>\d+)/$', 'responder', name='social-responder'),
	url('^borrar/(?P<mensaje_id>\d+)/$', 'borrar', name='social-borrar'),
	url('^conversacion/(?P<mensaje_id>\d+)/$', 'conversacion', name='social-conversacion'),
	url('^conversacion/(?P<mensaje_id>\d+)/page/(?P<page>\d+)/$', 'conversacion', name='social-conversacion'),
	url('^buscar/(?P<busqueda>([A-Za-z0-9_-]+))/(?P<opcion>[1-2]{1})/$', 'buscar', name='social-buscar'),
	#url('^buscar/(?P<busqueda>#([A-Za-z0-9_]+))/(?P<opcion>[1-2]{1})/page/(?P<page>\d+)/$', 'buscar', name='social-buscar'),


)

urls.py
#coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from actividades.models import *
from paginas.models import *
from paginas.feeds import *
from actividades.feeds import *

# añadido por las modificaciones en el django-registration
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

actividades_dict = {
    'queryset': Idiomas_actividad.objects.all(),
    'date_field': 'creado',
}

paginas_dict = {
    'queryset': Idiomas_pagina.objects.filter(pagina__estado='publicada',pagina__visibilidad='publica'),
    'date_field': 'creado',
}

entradas_dict = {
    'queryset': Idiomas_entrada.objects.filter(entrada__estado='publicada',entrada__visibilidad='publica'),
    'date_field': 'creado',
}


sitemap = {
    'paginas': GenericSitemap(paginas_dict, priority=0.5, changefreq='weekly'),
    'entradas': GenericSitemap(entradas_dict, priority=0.5, changefreq='weekly'), 
    'actividades': GenericSitemap(actividades_dict, priority=0.5, changefreq='weekly'), 
}

urlpatterns = patterns('',


	########## PERSONALIZACION DE LA ADMINISTRACIÓN ###########
	########## ACTIVIDADES #########
	url(r'^admin/recarga_miembros_actividad/$', 'actividades.admin_views.recarga_actividad', name='admin-recarga-actividad'),
	########## GRUPO #########
	url(r'^admin/recarga_miembros_grupo/$', 'grupos.admin_views.grupos_miembros_dependientes', name='admin-grupos-recarga-miembros-grupo'),
	
	########## PAGINAS #########
	url(r'^admin/recarga_entrada/$', 'paginas.admin_views.recarga_entrada', name='admin-entrada-recarga'),
	url(r'^admin/recarga_pagina/$', 'paginas.admin_views.recarga_pagina', name='admin-pagina-recarga'),

	########## ECONOMIA #########
	url(r'^admin/recarga_form_cuenta/$', 'economia.admin_views.eco_cuenta_codas_dependientes', name='admin-eco-recarga-form-cuenta'),
	url(r'^admin/recarga_form_intercambio_1/$', 'economia.admin_views.eco_cosas_dependientes_1', name='admin-eco-recarga-form-intercambio-1'),
	url(r'^admin/recarga_form_intercambio_2/$', 'economia.admin_views.eco_cosas_dependientes_2', name='admin-eco-recarga-form-intercambio-2'),
	url(r'^admin/recarga_form_intercambio_3/$', 'economia.admin_views.eco_cosas_dependientes_3', name='admin-eco-recarga-form-intercambio-3'),
	url(r'^admin/recarga_form_intercambio_4/$', 'economia.admin_views.eco_cosas_dependientes_4', name='admin-eco-recarga-form-intercambio-4'),
	
	url(r'^admin/', include(admin.site.urls)),

	########## INTERNALIZACION ###################################
	(r'^trans/', include('datatrans.urls')), #django-datatrans
	(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^rosetta/', include('rosetta.urls')),
	(r'^set_lang/(?P<lang>\w{2})/$','utilidades.views.set_lang'),

	########## PORTADA ###################################
	url(r'^$', 'portada.views.portada', name = "portada"),
	url(r'', include('portada.urls')),

	########## ACTIVIDADES ###################################
	(r'^actividad/', include('actividades.urls')),

	########## ECONOMIA ###################################
	(r'^economia/', include('economia.urls')),
	
	########## USUARIOS ###################################
	(r'^usuarios/', include('usuarios.urls')),
	
	########## DJANGO-ALLAUTH ###################################
	(r'^accounts/', include('allauth.urls')),
	
	########## Python Social Auth ###################################
	#url('', include('social.apps.django_app.urls', namespace='social')),
	#url('', include('django.contrib.auth.urls', namespace='auth')),
	
	########### LOGIN ###################################
	#url(r'^accounts/login/$', 'django.contrib.auth.views.login', name = "login"),
	#url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', kwargs=dict(next_page='/') , name = "logout"),
	#(r'^accounts/', include('registration.backends.default.urls')),

	########## twitter ###################################
	(r'^twitter/', include('twitter.urls')),

	########## GRUPOS ###################################
	(r'^grupos/', include('grupos.urls')),
	
	########## PAGINAS ###################################
	
	(r'^p/', include('paginas.urls')),
	
	########## PAGINAS ###################################
	
	(r'^ces/', include('ces.urls')),
	
	########## TINYMCE ###################################
	
	(r'^tinymce/', include('tinymce.urls')),
	
	########## SITEMAPS ###################################

	url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemap}),
	
	########## RSS ###################################
	
	url(r'^rss/entradas/$', Entradas_Generales_Feed(), name="rss-entradas-general"),
	url(r'^rss/entradas/(?P<simbolo>([^/]+))/$', Entradas_Grupo_Feed(), name="rss-entradas-grupo"),
	url(r'^rss/actividades/$', Actividades_Generales_Feed(), name="rss-actividades-general"),
	url(r'^rss/actividades/(?P<simbolo>([^/]+))/$', Actividades_Grupo_Feed(), name="rss-actividades-grupo"),
	
	########## CONFIGURACION ###################################
	

	(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1], 'django.views.static.serve',
	{'document_root': settings.MEDIA_ROOT}),
	
	# añadido por las modificaciones en el django-registration
	#override the default urls
	#url(r'^password/change/$',
				#auth_views.password_change,
				#name='password_change'),
	#url(r'^password/change/done/$',
				#auth_views.password_change_done,
				#name='password_change_done'),
	#url(r'^password/reset/$',
				#auth_views.password_reset,
				#name='password_reset'),
	#url(r'^password/reset/done/$',
				#auth_views.password_reset_done,
				#name='password_reset_done'),
	#url(r'^password/reset/complete/$',
				#auth_views.password_reset_complete,
				#name='password_reset_complete'),
	#url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
				#auth_views.password_reset_confirm,
				#name='password_reset_confirm'),

	##and now add the registration urls
	#url(r'', include('registration.backends.default.urls')),
)

#if 'rosetta' in settings.INSTALLED_APPS:
	#urlpatterns += patterns('',
		#url(r'^rosetta/', include('rosetta.urls')),
	#)

	
if settings.DEBUG:
	#urlpatterns += staticfiles_urlpatterns()
	urlpatterns += patterns('',
		#(r'^' + settings.STATIC_URL.lstrip('/'), include('appmedia.urls')),
		url(r'static/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.STATIC_ROOT,
	}),
)
			

apps/twitter/models.py
# coding=utf-8

from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
import re
from urllib import urlencode
from django.utils.translation import ugettext as _

############################################################################################################################

class Mensaje(models.Model):

	usuario = models.ForeignKey(User, related_name='usu_mensaje',editable=False)
	contenido = models.TextField(_(u"Contenido"),max_length = 500)
	reescrito = models.BooleanField(_(u"Reenviar"), default=False, blank=True)
	respuesta = models.IntegerField(_(u"Respuesta"), null=True, blank=True)
	activo = models.BooleanField(_(u"Activo"), default=True)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)

	def __unicode__(self):
		return self.contenido
		
	def filtrar(self):
		"""Filtra XSS enlaza hashtags, menciones y enlaces """
		t = self.contenido

		#Anti XSS
		t = t.replace('&','&amp;')
		t = t.replace('<','&lt;')
		t = t.replace('>','&gt;')
		t = t.replace('\'','&#39;')
		t = t.replace('"','&quot;')

		hashtags = re.findall('#[a-zA-Z][a-zA-Z0-9_-]*', t)
		for hashtag in hashtags:
			"""El simbolo '#' no puedo mandarlo en las variables de expresion regular por url así que lo quito."""
			v = hashtag.replace('#','')
			t = t.replace(hashtag, '<a href="/social/buscar/%s/1">%s</a>' % (v, hashtag))

		links = re.findall('http\\:\\/\\/[^ ]+', t)
		for link in links:
			t = t.replace(link, '<a href="%s">%s</a>' % (link, link))

		menciones = re.findall('\\@[a-zA-Z0-9_]+', t)
		for mencion in menciones:
			t = t.replace(mencion, '<a href="/social/perfil_social/%s/">%s</a>' % (mencion[1:], mencion))

		return t

############################################################################################################################

class Votos_mensaje(models.Model):

	usuario = models.ForeignKey(User, related_name='usu_voto_mensaje')
	mensaje = models.ForeignKey(Mensaje, related_name='votos_mensaje')
	puntuacion = models.PositiveIntegerField(_(u"Valoración"),default=0,editable=False)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)

	class Meta:
		verbose_name = _(u'voto del mensaje')
		verbose_name_plural = _(u'votos de los mensajes')
		
############################################################################################################################


class Seguimiento(models.Model):
	seguidor = models.ForeignKey(User, related_name='seguidor',editable=False)
	seguido = models.ForeignKey(User, related_name='seguidos')
	activo = models.BooleanField(_(u"Activo"), default=True)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)

############################################################################################################################

apps/twitter/forms.py
# coding=utf-8
from django import forms
#from django.contrib.localflavor.es.forms import *
from django.utils.translation import ugettext as _
from twitter.models import *
#from utilidades.combox import *
from django.forms.extras.widgets import *


############################################################################################################################

class Form_seguir(forms.Form):
	
   usu = forms.IntegerField(widget=forms.HiddenInput())
   accion = forms.IntegerField(widget=forms.HiddenInput())

############################################################################################################################

#class Form_escribir(forms.ModelForm):
	
	#class Meta:
		#model = Mensaje
		#fields = ('usuario', 'contenido')
		#widgets = {
			#'usuario': forms.HiddenInput(),
			#}


############################################################################################################################
class Form_escribir(forms.Form):
	
	usu = forms.IntegerField(widget=forms.HiddenInput())
	respuesta = forms.IntegerField(widget=forms.HiddenInput())
	contenido = forms.CharField(max_length=255, widget=forms.Textarea())
	
	"""El clean me lanza un error que no sé que hacer
	Exception Type:	KeyError
	Exception Value:'contenido'
	Exception Location:	/home/mene/www/virtualenv/market/apps/social/forms.py in clean, line 45

	/home/mene/www/virtualenv/market/apps/social/views.py in escribir
	line 63:  if form.is_valid(): 
	"""
	
	#def clean(self):
		
		#if self.cleaned_data['contenido'] == u'':
			#raise forms.ValidationError(_(u'Debes escribir algo.'))
		#else:
			#return self.cleaned_data

apps/twitter/templates/social/mensajes.html
{% extends "base.html" %}

{% block title %} Mensajes {% endblock %}

{% block content %}

<div class='row display'>
<section class="ten columns">
{% if mensajes|length %}
	<header>
	<h4>Conversación completa.<h4>
	<hr/>
	</header>	

	{% for m in mensajes %}
	<article>
		<header>
			<h5>{{ m.usuario.get_full_name }} (<a href="{% url 'social-perfil' m.usuario %}">@{{ m.usuario }}</a>)</h5>
		</header>
		{{ m.filtrar|safe|linebreaksbr }}
		<footer>
			<p>
				{% if m.reescrito %}
					<strong>Reescrito por <a href="{% url 'social-perfil' m.reescrito_por %}">@{{ m.reescrito_por }}</a></strong>
				{% endif %}
				
				{% if m.reescrito_por == request.user %}
					<a href="{% url 'social-borrar' m.mensaje_id %}">Borrar reescrito</a><br>
				{% endif %}
				
				<br>
				
				{% if m.respuesta %}
					<a href="{% url 'social-conversacion' m.id %}">Ver conversacion completa</a><br>
				{% endif %}
				
				<strong>Publicado: {{ m.creado }}</strong>
				{% if m.usuario != request.user %}
					<a href="{% url 'social-reescribir' m.id %}"><i class="icon-retweet"></i>Reescribir</a>
					<a href="{% url 'social-responder' m.id %}"><i class="icon-share-alt"></i>Responder</a>
				{% endif %}
				
				{% if m.usuario == request.user %}
					<a href="{% url 'social-borrar' m.id %}"><i class="icon-trash"></i>Borrar</a>
				{% endif %}
			</p>
			<hr/>
		</footer>
	</article>
	{% endfor %}
{% else %}
	<header>
		<h3>No hay ningun mensaje</h3>
	</header>
{% endif %}
</section>


<section id="tendencias">

	{% if index %}
		<h3>Trending Topics</h3>
		{% for topic in trending %}
			<a href="/twitter/buscar/?busqueda=%23{{ topic }}">#{{ topic }}</a><br>
		{% endfor %}
		<br><h3>Quizás te interese seguir a</h3>
		{% for u in seguir %}
			<a href="/twitter/profile/{{ u }}/">{{ u.get_full_name }} (@{{ u }})</a><br>
			<form action="/twitter/follow/" method="post">
				{% csrf_token %}
				<input type="hidden" name="user" value="{{ u }}">
				<input class="btn btn-success" type="submit" value="Seguir"><br>
			</form>
		{% endfor %}
	{% endif %}

</section>
	
</div> <!--  Fin contenidos -->

{% endblock %}

apps/twitter/templates/social/perfil_social.html
{% extends "base.html" %}
{% load i18n localeurl_tags thumbnail %}


{% block title %}{% trans "Ficha social de este usuario" %}{% endblock %}

{% block content %}

<section class="row">
	<header class="small-12 columns">
		<h4>{% trans "Ficha social de este usuario" %}</h6>
	</header>

	<article>

       <table class="small-6 columns">

       <tr><td colspan="2" ><h2>{{ este_perfil }}</h2></td></tr>

           <tr><td>&nbsp;</td>
               <td>
					{% for i in este_perfil.fotos_personales.all %}
					{% thumbnail i.foto "48x48" as im %}
						<img src="{{ im.url }}" alt="{{ i.foto.name }}"  width="{{ im.width }}" height="{{ im.height }}"/>{% if not forloop.last %}&nbsp;{% endif %}
					{% endthumbnail %}
					{% endfor %}
					
					{% if request.user != este_perfil.usuario %}
					<form action="{% url 'social-seguir' %}" method="POST">
						{% csrf_token %}
							<input type="hidden" name="usu" value="{{ este_perfil.usuario.pk }}" id="id_usu" />	
						{% if es_seguido %}				
							<input type="hidden" name="accion" value="0" id="id_accion" />
							<input type="submit" value="Dejar de seguir" class="tiny success button"/>
						{% else %}
							<input type="hidden" name="accion" value="1" id="id_accion" />
							<input type="submit" value="Seguir" class="tiny success button"/>	
						{% endif %}				
					</form>
					{% endif %}	
               </td>
           </tr>
           <tr><td>{% trans "Usuario" %}</td>
								<td><a href="{% url 'social-perfil' este_perfil.usuario %}">@{{ este_perfil.usuario }}</a>	
								({% if not este_perfil.ocultar_nombre %}
										{{ este_perfil.nombre }}
									{% endif %}	
									{% if not este_perfil.ocultar_apellidos %}
										{{ este_perfil.apellidos }}
									{% endif %}	)
								</td>
			</tr>
           
           <tr><td>{% trans "Sus grupos" %}</td>
				<td>
					{% for grupo in grupos %}
						{{ grupo.grupo }}{% if not forloop.last %},{% endif %}
					{% endfor %}               
				</td>
           </tr>
           <tr><td>{% trans "Pais" %}</td><td>{{ este_perfil.pais }}</td></tr>
           <tr><td>{% trans "Provincia" %}</td><td>{{ este_perfil.provincia }}</td></tr>
           <tr><td>{% trans "Poblacion" %}</td><td>{{ este_perfil.poblacion }}</td></tr>
           {% if not este_perfil.ocultar_direccion %}
           <tr><td>{% trans "Dirección" %}</td><td>{{ este_perfil.direccion }}</td></tr>
           {% endif %}
           {% if not este_perfil.ocultar_codigo_postal %}
           <tr><td>{% trans "CP" %}</td><td>{{ este_perfil.codigo_postal }}</td></tr>
           {% endif %}
           <tr><td>{% trans "Teléfono" %}</td><td>{{ este_perfil.telefono }}</td></tr>
           <tr><td>{% trans "Descripción personal" %}</td><td>{{ este_perfil.descripcion|removetags:"iframe script"|safe }}</td></tr>
           {% for item in este_perfil.social_usu.all %}
           <tr>
				<td>{{ item.nombre }}:</td><td>{{ item.referencia }}</td>
           </tr>
           {% endfor %}
           
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
           <tr><td>{% trans "Número de logins" %}</td><td>{{ n_logins }}</td></tr>
           <tr><td>{% trans "Registrado hace:" %}</td><td>{{ este_perfil.creado|timesince }}</td></tr>
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>

       </table>
       
       <div class="small-6 columns">
       <br><div><b>{% trans "Ultimas actividades" %}</b> <a href="{% url 'actividad-usuario' este_perfil.usuario.pk %}">{% trans "Ver todas" %}</a> ({{ n_actividades }})</div>
       <ul>
		{% for item in ult_actividades %}
			<li><a href="{{ item.get_absolute_url }}" title="{{ item }}">{{ item }}</a> | {% trans "Hace: " %}{{ item.creado|timesince }}</li>
		{% empty %}
			<li>{% trans "No hay registros" %}</li>
		{% endfor %}
		</ul>
		
		<br><div><b>{% trans 'Ultimas entradas' %}</b> <a href="{% url 'paginas-entradas-usu' este_perfil %}">{% trans "Ver todas" %}</a> ({{ n_entradas }})</div>
		<ul>
		{% for item in ult_entradas %}
			<li><a href="{{ item.get_absolute_url }}" title="{{ item }}">{{ item }}</a> | {% trans "Hace: " %}{{ item.creada|timesince }}</li>
		{% empty %}
			<li>{% trans "No hay registros" %}</li>
		{% endfor %}
		</ul>
		
		<br><div><b>{% trans "Ultimos intercambios públicos" %}</b> <a href="{% url 'economia-i-p-usuario' este_perfil.usuario.pk %}">{% trans "Ver todos" %}</a> ({{ n_intercambios }})</div>
		<ul>
		{% for item in ult_intercambios_p %}
			<li><a href="{% url 'social-perfil' item.origen %}">@{{ item.origen }}</a> > {{ item }} > <a href="{% url 'social-perfil' item.destino %}">@{{ item.destino }}</a> ({{ item.creado|timesince }})</li>
		{% empty %}
			<li>{% trans "No hay registros" %}</li>
		{% endfor %}
		</ul>
       </div>
       

       
	</article>


{% endblock %}

apps/twitter/templates/social/perfil_social_seguridad.html
{% extends "base.html" %}
{% load i18n localeurl_tags thumbnail %}


{% block title %}{% trans "Ficha social de este usuario" %}{% endblock %}

{% block content %}

<section class="row">
	<header class="small-12 columns">
		<h4>{% trans "Ficha social de este usuario" %}</h6>
	</header>

	<article>

       <table class="small-12 columns">

       <tr><td colspan="2" ><h2>{{ este_perfil }}</h2></td></tr>

           <tr><td>&nbsp;</td>
               <td>
					{% for i in este_perfil.fotos_personales.all %}
					{% thumbnail i.foto "48x48" as im %}
						<img src="{{ im.url }}" alt="{{ i.foto.name }}"  width="{{ im.width }}" height="{{ im.height }}"/>{% if not forloop.last %}&nbsp;{% endif %}
					{% endthumbnail %}
					{% endfor %}
					
					{% if request.user != este_perfil.usuario %}
					<form action="{% url 'social-seguir' %}" method="POST">
						{% csrf_token %}
							<input type="hidden" name="usu" value="{{ este_perfil.usuario.pk }}" id="id_usu" />	
						{% if es_seguido %}				
							<input type="hidden" name="accion" value="0" id="id_accion" />
							<input type="submit" value="Dejar de seguir" class="tiny success button"/>
						{% else %}
							<input type="hidden" name="accion" value="1" id="id_accion" />
							<input type="submit" value="Seguir" class="tiny success button"/>	
						{% endif %}				
					</form>
					{% endif %}	
               </td>
           </tr>
           <tr><td>{% trans "Usuario" %}</td>
								<td><a href="{% url 'social-perfil' este_perfil.usuario %}">@{{ este_perfil.usuario }}</a>	
								({% if not este_perfil.ocultar_nombre %}
										{{ este_perfil.nombre }}
									{% endif %}	
									{% if not este_perfil.ocultar_apellidos %}
										{{ este_perfil.apellidos }}
									{% endif %}	)
								</td>
			</tr>
           
           <tr><td>{% trans "Sus grupos" %}</td>
				<td>
					{% for grupo in grupos %}
						{{ grupo.grupo }}{% if not forloop.last %},{% endif %}
					{% endfor %}               
				</td>
           </tr>
           <tr><td>{% trans "Siguiendo" %}</td><td>{{ seguidor|length  }}</td></tr>
           <tr><td>{% trans "Siguiendo a" %}</td>
				<td>
					{% for usu in seguidor %}
						<a href="{% url 'social-perfil' usu.seguido %}">@{{ usu.seguido }}</a> {% if not forloop.last %},{% endif %}
					{% endfor %}               
				</td>
           </tr>
           <tr><td>{% trans "Seguidores" %}</td><td>{{ seguido|length }}</td></tr>
           <tr><td>{% trans "Seguido por" %}</td>
				<td>
					{% for usu in seguido %}
						<a href="{% url 'social-perfil' usu.seguidor %}">@{{ usu.seguidor }}</a> {% if not forloop.last %},{% endif %}
					{% endfor %}               
				</td>
           </tr>
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
           
           <tr><td>{% trans "Pais" %}</td><td>{{ este_perfil.pais }}</td></tr>
           <tr><td>{% trans "Provincia" %}</td><td>{{ este_perfil.provincia }}</td></tr>
           <tr><td>{% trans "Poblacion" %}</td><td>{{ este_perfil.poblacion }}</td></tr>
           {% if not este_perfil.ocultar_direccion %}
           <tr><td>{% trans "Dirección" %}</td><td>{{ este_perfil.direccion }}</td></tr>
           {% endif %}
           {% if not este_perfil.ocultar_codigo_postal %}
           <tr><td>{% trans "CP" %}</td><td>{{ este_perfil.codigo_postal }}</td></tr>
           {% endif %}
           <tr><td>{% trans "Teléfono" %}</td><td>{{ este_perfil.telefono }}</td></tr>
           <tr><td>{% trans "Descripción personal" %}</td><td>{{ este_perfil.descripcion }}</td></tr>
           {% for item in este_perfil.social_usu.all %}
           <tr>
				<td>{{ item.nombre }}:</td><td>{{ item.referencia }}</td>
           </tr>
           {% endfor %}
           
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>
           <tr><td>{% trans "Número de logins" %}</td><td>{{ este_perfil.visitas_propias }}</td></tr>
           <tr><td>{% trans "Registrado hace:" %}</td><td>{{ este_perfil.creado|timesince }}</td></tr>
           <tr><td>&nbsp;</td><td>&nbsp;</td></tr>

       </table>
       
	</article>


{% endblock %}

apps/twitter/templates/social/reescribir.html
{% extends "base.html" %}

{% block title %} Reescibir {% endblock %}

{% block content %}

<div id="contenidos" class="contenedor_contenido">

	<p>
		Confirme que desea reescribir: {{ mensaje.filtrar|safe|linebreaksbr }}<br>
		<form action="{% url 'social-reescribir' mensaje.id %}" method="post">
			{% csrf_token %}
			<input class="btn btn-success" type="submit" value="Reescribir" name="confirma">
			<a class="btn btn-danger" href="{% url 'portada' %}">No reescribir</a>
		</form>
	</p>
	
</div>
{% endblock %}

apps/twitter/templates/social/responder.html
{% extends "base.html" %}

{% block title %} Responder mensaje {% endblock %}

{% block content %}

<div id="contenidos" class="contenedor_contenido">

	<p>Responder a este mensaje</p>

	<p>{{ mensaje.usuario.get_full_name }} (<a href="{% url 'social-perfil' mensaje.usuario %}">@{{ mensaje.usuario }}</a>)</p>

	<p>{{ mensaje.filtrar|safe|linebreaksbr }}</p>

	<p><strong>Publicado: {{ mensaje.creado }}</strong></p>

	<form action="{% url 'social-escribir' %}" method="POST">
		{% csrf_token %}
		<input type="hidden" name="usu" value="{{ request.user.pk }}" id="id_usu" />
		<input type="hidden" name="respuesta" value="{{ mensaje.pk }}" id="id_respuesta" />
		<textarea  name="contenido"  id="id_contenido" rows="10" cols="40">@{{ mensaje.usuario }}</textarea>
		<button type="submit">Responder</button>
		<a class="btn btn-danger" href="{% url 'portada' %}">No responder</a>
	</form>

</div>

{% endblock %}