apps/actividades/urls.py
# coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

#Eliminado en django 1.6
#from django.conf.urls.defaults import *
from django.conf.urls import patterns, url
from actividades.models import *
from actividades.views import *

urlpatterns = patterns('actividades.views',

	url(r'^todas/$', 'actividades', name='actividades'),
	url(r'^usuario/(?P<id_usuario>\d+)/$', 'actividades', name='actividad-usuario'),
	url(r'^(?P<clase>(bienes|servicios))/$', 'actividades', name='actividad-clase'),
	url(r'^(?P<simbolo>([^/]+))/actividades/$', 'actividades_grupo', name='actividad-grupo'),
	url(r'^(?P<clase>(bienes|servicios))/(?P<tipo>(oferta|demanda))/(?P<id_objeto>\d+)/(?P<slug>([^/]+))$', 'ver_actividad', name="ver-actividad"),
	url(r'^valorar_actividades/(?P<pagina>\d+)/(?P<ajax>(si|no))/$', 'valorar_actividades', name='actividad-valorar'),
	url(r'^valorar_actividad/$', 'valorar_actividad', name='actividad-valorar-ajax'),
	url(r'^busqueda_actividad/$', 'busqueda_actividad', name='actividad-busqueda'),
	url(r'^favoritos/$', 'mis_favoritos', name='actividad-mis-favoritos'), 
	url(r'^tag/(?P<tag>([A-Za-z0-9_-]+))','actividades_clasificadas', name='actividad-tag'),
	url(r'^categoria/(?P<id_categoria>\d+)/$','actividades_clasificadas', name='actividad-categoria'),

)

urls.py
#coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from actividades.models import *
from paginas.models import *
from paginas.feeds import *
from actividades.feeds import *

# añadido por las modificaciones en el django-registration
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

actividades_dict = {
    'queryset': Idiomas_actividad.objects.all(),
    'date_field': 'creado',
}

paginas_dict = {
    'queryset': Idiomas_pagina.objects.filter(pagina__estado='publicada',pagina__visibilidad='publica'),
    'date_field': 'creado',
}

entradas_dict = {
    'queryset': Idiomas_entrada.objects.filter(entrada__estado='publicada',entrada__visibilidad='publica'),
    'date_field': 'creado',
}


sitemap = {
    'paginas': GenericSitemap(paginas_dict, priority=0.5, changefreq='weekly'),
    'entradas': GenericSitemap(entradas_dict, priority=0.5, changefreq='weekly'), 
    'actividades': GenericSitemap(actividades_dict, priority=0.5, changefreq='weekly'), 
}

urlpatterns = patterns('',


	########## PERSONALIZACION DE LA ADMINISTRACIÓN ###########
	########## ACTIVIDADES #########
	url(r'^admin/recarga_miembros_actividad/$', 'actividades.admin_views.recarga_actividad', name='admin-recarga-actividad'),
	########## GRUPO #########
	url(r'^admin/recarga_miembros_grupo/$', 'grupos.admin_views.grupos_miembros_dependientes', name='admin-grupos-recarga-miembros-grupo'),
	
	########## PAGINAS #########
	url(r'^admin/recarga_entrada/$', 'paginas.admin_views.recarga_entrada', name='admin-entrada-recarga'),
	url(r'^admin/recarga_pagina/$', 'paginas.admin_views.recarga_pagina', name='admin-pagina-recarga'),

	########## ECONOMIA #########
	url(r'^admin/recarga_form_cuenta/$', 'economia.admin_views.eco_cuenta_codas_dependientes', name='admin-eco-recarga-form-cuenta'),
	url(r'^admin/recarga_form_intercambio_1/$', 'economia.admin_views.eco_cosas_dependientes_1', name='admin-eco-recarga-form-intercambio-1'),
	url(r'^admin/recarga_form_intercambio_2/$', 'economia.admin_views.eco_cosas_dependientes_2', name='admin-eco-recarga-form-intercambio-2'),
	url(r'^admin/recarga_form_intercambio_3/$', 'economia.admin_views.eco_cosas_dependientes_3', name='admin-eco-recarga-form-intercambio-3'),
	url(r'^admin/recarga_form_intercambio_4/$', 'economia.admin_views.eco_cosas_dependientes_4', name='admin-eco-recarga-form-intercambio-4'),
	
	url(r'^admin/', include(admin.site.urls)),

	########## INTERNALIZACION ###################################
	(r'^trans/', include('datatrans.urls')), #django-datatrans
	(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^rosetta/', include('rosetta.urls')),
	(r'^set_lang/(?P<lang>\w{2})/$','utilidades.views.set_lang'),

	########## PORTADA ###################################
	url(r'^$', 'portada.views.portada', name = "portada"),
	url(r'', include('portada.urls')),

	########## ACTIVIDADES ###################################
	(r'^actividad/', include('actividades.urls')),

	########## ECONOMIA ###################################
	(r'^economia/', include('economia.urls')),
	
	########## USUARIOS ###################################
	(r'^usuarios/', include('usuarios.urls')),
	
	########## DJANGO-ALLAUTH ###################################
	(r'^accounts/', include('allauth.urls')),
	
	########## Python Social Auth ###################################
	#url('', include('social.apps.django_app.urls', namespace='social')),
	#url('', include('django.contrib.auth.urls', namespace='auth')),
	
	########### LOGIN ###################################
	#url(r'^accounts/login/$', 'django.contrib.auth.views.login', name = "login"),
	#url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', kwargs=dict(next_page='/') , name = "logout"),
	#(r'^accounts/', include('registration.backends.default.urls')),

	########## twitter ###################################
	(r'^twitter/', include('twitter.urls')),

	########## GRUPOS ###################################
	(r'^grupos/', include('grupos.urls')),
	
	########## PAGINAS ###################################
	
	(r'^p/', include('paginas.urls')),
	
	########## PAGINAS ###################################
	
	(r'^ces/', include('ces.urls')),
	
	########## TINYMCE ###################################
	
	(r'^tinymce/', include('tinymce.urls')),
	
	########## SITEMAPS ###################################

	url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemap}),
	
	########## RSS ###################################
	
	url(r'^rss/entradas/$', Entradas_Generales_Feed(), name="rss-entradas-general"),
	url(r'^rss/entradas/(?P<simbolo>([^/]+))/$', Entradas_Grupo_Feed(), name="rss-entradas-grupo"),
	url(r'^rss/actividades/$', Actividades_Generales_Feed(), name="rss-actividades-general"),
	url(r'^rss/actividades/(?P<simbolo>([^/]+))/$', Actividades_Grupo_Feed(), name="rss-actividades-grupo"),
	
	########## CONFIGURACION ###################################
	

	(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1], 'django.views.static.serve',
	{'document_root': settings.MEDIA_ROOT}),
	
	# añadido por las modificaciones en el django-registration
	#override the default urls
	#url(r'^password/change/$',
				#auth_views.password_change,
				#name='password_change'),
	#url(r'^password/change/done/$',
				#auth_views.password_change_done,
				#name='password_change_done'),
	#url(r'^password/reset/$',
				#auth_views.password_reset,
				#name='password_reset'),
	#url(r'^password/reset/done/$',
				#auth_views.password_reset_done,
				#name='password_reset_done'),
	#url(r'^password/reset/complete/$',
				#auth_views.password_reset_complete,
				#name='password_reset_complete'),
	#url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
				#auth_views.password_reset_confirm,
				#name='password_reset_confirm'),

	##and now add the registration urls
	#url(r'', include('registration.backends.default.urls')),
)

#if 'rosetta' in settings.INSTALLED_APPS:
	#urlpatterns += patterns('',
		#url(r'^rosetta/', include('rosetta.urls')),
	#)

	
if settings.DEBUG:
	#urlpatterns += staticfiles_urlpatterns()
	urlpatterns += patterns('',
		#(r'^' + settings.STATIC_URL.lstrip('/'), include('appmedia.urls')),
		url(r'static/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.STATIC_ROOT,
	}),
)
			

apps/actividades/forms.py
# coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from django import forms
from actividades.models import *
from django.utils.translation import ugettext as _
from utilidades.combox import *
from actividades.models import *
from grupos.models import *
from django.forms import ModelMultipleChoiceField
from django.forms.models import BaseInlineFormSet
from django.db.models import Q



############################################################################################################################

class Form_valorar_actividad(forms.Form):
	
   objeto = forms.IntegerField(widget=forms.HiddenInput())
   pagina = forms.IntegerField(widget=forms.HiddenInput())
   n_paginas = forms.IntegerField(widget=forms.HiddenInput())
   retorno = forms.IntegerField(widget=forms.HiddenInput())
   me_gusta_para_mi = forms.IntegerField()
   rating_para_mi = forms.IntegerField()
   bien_comun = forms.IntegerField()
   rating_para_bien_comun = forms.IntegerField()
   comentario = forms.CharField(widget=forms.Textarea(), label=_(u"Comentario"),max_length=400,required=False)

############################################################################################################################
class Form_busqueda(forms.Form):
	
	busqueda = forms.CharField(max_length=100, label=_(u"Búsqueda"),required=False)
	clase = forms.ChoiceField(choices=CLASE_ACTIVIDAD, label=_(u"Clase"),required=False)
	tipo = forms.ChoiceField(choices=TIPO_ACTIVIDAD, label=_(u"Tipo"),required=False)
	grupos = forms.ChoiceField(choices=GRUPOS_BUSQUEDA, label=_(u"En qué grupos"),required=False)
	orden = forms.ChoiceField(choices=ORDEN, label=_(u"Ordenar por"),required=False)
	
############################################################################################################################
	
class Form_categoria_actividad_admin(forms.ModelForm):

	"""Cargo en los select solo los datos relativos a los grupos de los que el usuario registrado en el sistema es administrador"""
	class Meta:
		model = Categoria
		
	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None) # Now you can access request anywhere in your form methods by using self.request. 
		user = kwargs.pop('user', None)
		super(Form_categoria_actividad_admin, self).__init__(*args, **kwargs)
		if user.is_superuser:
			self.fields['grupo'].queryset = Grupo.objects.all()
		else:
			qs_grupos_administrados = Miembro.objects.filter(usuario=user,activo=True,nivel=u'Administrador').values_list('grupo', flat=True)
			if len(qs_grupos_administrados)>0:
				self.fields['grupo'].queryset = Grupo.objects.filter(pk__in=qs_grupos_administrados,activo=True)
			else:
				qs_grupos = Miembro.objects.filter(usuario=user).values_list('grupo', flat=True)
				
	def clean(self):
		try:
			grupos = self.cleaned_data['grupo']
			usuario = self.request.user

			#----- Grupos --------
			n_grupos = len(grupos)
			if n_grupos == 0 and not usuario.is_superuser:
				#El Superadmin puede publicar sin que pernezca a ningún grupo para que no lo controlen los Admin de los grupos
				raise forms.ValidationError(_(u"El campo grupo es obligatorio."))
			return self.cleaned_data
		except KeyError:
			raise forms.ValidationError(_("Soluciona estos problemas"), code='invalid')

	
############################################################################################################################
	
class Form_actividad_admin(forms.ModelForm):

	"""Cargo en los select solo los datos relativos a los grupos de los que el usuario registrado en el sistema es administrador"""
	class Meta:
		model = Actividad
		fields = ('grupo','superadmin','usuario','clase','tipo','categoria','precio_moneda_social','activo')
		
	def __init__(self, *args, **kwargs):
		self.request = kwargs.pop('request', None) # Now you can access request anywhere in your form methods by using self.request. 
		user = kwargs.pop('user', None)
		super(Form_actividad_admin, self).__init__(*args, **kwargs)

		if user.is_superuser:
			self.fields['grupo'].queryset = Grupo.objects.all()
			self.fields['usuario'].queryset = User.objects.all()
			self.fields['categoria'].queryset = Categoria.objects.all()
		else:
			qs_grupos_administrados = Miembro.objects.filter(usuario=user,activo=True,nivel=u'Administrador').values_list('grupo', flat=True)
			if len(qs_grupos_administrados)>0:
				qs_miembros_administrados = Miembro.objects.filter(grupo__in=qs_grupos_administrados,activo=True).values_list('usuario', flat=True)
				self.fields['grupo'].queryset = Grupo.objects.filter(pk__in=qs_grupos_administrados,activo=True)
				self.fields['usuario'].queryset = User.objects.filter(pk__in=qs_miembros_administrados)
				self.fields['categoria'].queryset = Categoria.objects.filter(Q(grupo__in=qs_grupos_administrados) | Q(superadmin=True))
			else:
				qs_grupos = Miembro.objects.filter(usuario=user).values_list('grupo', flat=True)
				self.fields['grupo'].queryset = Grupo.objects.filter(pk__in=qs_grupos,activo=True)
				self.fields['usuario'].queryset = User.objects.filter(pk=user.pk)
				self.fields['categoria'].queryset = Categoria.objects.filter(Q(grupo__in=qs_grupos) | Q(superadmin=True))
				
	def clean_precio_moneda_social(self):
		precio_moneda_social = self.cleaned_data['precio_moneda_social']
		if precio_moneda_social <= 0:
			raise forms.ValidationError(_(u"Introduce una cantidad positiva."))
		return self.cleaned_data['precio_moneda_social']
	

	def clean(self):
		try:
			grupos = self.cleaned_data['grupo']
			usuario = self.cleaned_data['usuario']
			categoria = self.cleaned_data['categoria']
			
			#----- Grupos --------
			n_grupos = len(grupos)
			if n_grupos == 0 and not usuario.is_superuser:
				#El Superadmin puede publicar sin que pernezca a ningún grupo para que no lo controlen los Admin de los grupos
				raise forms.ValidationError(_(u"El campo grupo es obligatorio."))
			#----- Usuario --------
			n_usuario = Miembro.objects.filter(grupo__in=grupos,usuario=usuario,activo=True).count()
			if n_usuario == 0 and not usuario.is_superuser:
				#El Superadmin puede publicar sin que pernezca a ningún grupo para que no lo controlen los Admin de los grupos
				raise forms.ValidationError(_(u"El usuario elegido no pertenece a ninguno de los grupos seleccionados."))
			#------ Categoria ---------
			if categoria and categoria.superadmin == False:
				# Al superadmin que puede publicar sin grupos no se le controla.
				if n_grupos > 0:
					n_categoria = Categoria.objects.filter(pk=categoria.pk,grupo__in=grupos).count()
					if n_categoria == 0:
						raise forms.ValidationError(_(u"La categoria elegida no pertenece a ninuno de los grupos selecionados"))
			
			return self.cleaned_data
		except KeyError:
			raise forms.ValidationError(_("Soluciona estos problemas"), code='invalid')


############################################################################################################################	
class Form_Actividad(forms.ModelForm):

	class Meta:
		model = Actividad

	def __init__(self, *args, **kwargs):
		user = kwargs.pop('user', None)
		super(Form_Actividad, self).__init__(*args, **kwargs)
		self.fields['grupo'].queryset = Miembro.objects.filter(usuario=user).values('grupo')

		

#######################################################################################################################################################

class Idioma_requerido_formset(BaseInlineFormSet):

	def clean(self):
		super(Idioma_requerido_formset, self).clean()
		for error in self.errors:
			if error:
				return
			completed = 0
		for cleaned_data in self.cleaned_data:
			if cleaned_data and not cleaned_data.get('DELETE', False):
				completed += 1

		if completed < 1:
			raise forms.ValidationError(_("Es necesario introducir al menos un idioma para la actividad."))

		
############################################################################################################################

apps/actividades/templates/actividades/busqueda.html
{% extends "base.html" %}
{% load i18n localeurl_tags %}


{% block title %}{% trans "Busqueda de actividades" %} {% endblock %}

{% block content %}

{% include "actividades/form_busqueda.html" %}

<div class="row" id="contendor-central">

<section id="listado">
{% if busqueda_qs %}
	<header class="small-12 columns">
		{% trans "Hemos encontrado estos resultados para tu búsqueda." %}
	</header>
		{% for actividad in n_paginas.object_list %}
			{% ifchanged %}
				{% if user.is_authenticated %}
					{% include "actividades/listado_1.html" %}
				{% else %}
					{% include "actividades/listado_3.html" %}
				{% endif %}
			{% endifchanged %}
		{% endfor %}
		
		<div id="cargando-paginas" class="pelotica-invisible"></div>
				
	{% else %}
		<header  class="small-12 columns">
			<div class="panel">{% trans "Tu búsqueda no da ningún resultado" %}</div>
		</header>
	{% endif %}
</section>

</div> <!--Fin contendor-central-->



<script type="text/javascript">
	// Variables globales de scroll
	{% if n_paginas.object_list and n_paginas.paginator.num_pages > 1 %}
		var page = {{ n_paginas.number }}; // The latest page loaded
		var n_paginas = {{ n_paginas.paginator.num_pages }};
	{% else %}
		var page = 1;
		var n_paginas = 1;
	{% endif %}
	
	var loadOnScroll = function() {
//  		if($(window).scrollTop() == $(document).height() - $(window).height()){
//  			if ($(window).scrollTop() > $(document).height() - ($(window).height()*2)) {
			if ($(window).scrollTop() > $(document).height() - ($(window).height()*1.2)) {
			// temporarily unhook the scroll event watcher so we don't call a bunch of times in a row
 			$(window).unbind();
			// execute the load function below 
			cargar_paginas();
// 			alert('Funciona');
		}
	};

	var cargar_paginas = function() {
		page = page + 1;
		if (page > n_paginas) {
// 				alert(page)
			return false
		} else {
// 			alert(page + ' >>')
			$('#cargando-paginas').removeClass("pelotica-invisible").addClass("pelotica-visible");
			$.ajax({
				url: "{% url 'actividad-busqueda' %}?page=" + page,
				success: function(html)	{
					if(html){
						$("#listado").append(html);
 						$('#cargando-paginas').removeClass("pelotica-visible").addClass("pelotica-invisible");
// 						$('#cargando-paginas').show(1000);
					}else{
						$('#cargando-paginas').html('<center>No hay más favoritos..</center>');
					}
				},
				complete: function(data, textStatus){
					// Turn the scroll monitor back on
					$(window).bind('scroll', loadOnScroll);
				}
			});
		}
	};

</script>


{% endblock %}

apps/actividades/templates/actividades/clases.html
{% extends "base.html" %}
{% load i18n localeurl_tags %}


{% block title %} {{ situacion|upper }} {% endblock %}

{% block content %}

{% include "actividades/form_busqueda.html" %}

<div class="row" id="contendor-central">
	<section id="listado">
		{% if actividades %}
			<div class="small-12 columns"> 
				<h3>{% trans "Actividades" %} > {{ situacion }}</h3>
			</div>
			<div class="small-12 columns"> 
				{% if rss == 'todas' %}
					<a href="{% url 'rss-actividades-general' %}">
						<img src="{{ STATIC_URL }}imagenes/interface/ico_rss.gif" alt="Suscribirse a las actividades de Play Circular"/> 
						Suscribirse a las actividades de Play Circular
					</a>
				{% endif %}
				{% if rss == 'grupo' %}
					<a href="{% url 'rss-actividades-grupo' grupo %}">
						<img src="{{ STATIC_URL }}imagenes/interface/ico_rss.gif" alt="Suscribirse a las actividades del grupo {{ grupo }}"/> 
						Suscribirse a las actividades del grupo {{ grupo }}
					</a>
				{% endif %}
			</div>
			{% for actividad in n_paginas.object_list %}
				{% if user.is_authenticated %}
					{% include "actividades/listado_1.html" %}
				{% else %}
					{% include "actividades/listado_3.html" %}
				{% endif %}
			{% endfor %}
			<div id="cargando-paginas" class="pelotica-invisible"></div>
		{% else %}
			<header class="small-12 columns">
				<div class="panel">{% trans "Tu búsqueda no da ningún resultado" %}</div>
			</header>
		{% endif %}

	</section>
</div> <!--Fin contendor-central-->



<script type="text/javascript">
	// Variables globales de scroll
	{% if n_paginas.object_list and n_paginas.paginator.num_pages > 1 %}
		var page = {{ n_paginas.number }}; // The latest page loaded
		var n_paginas = {{ n_paginas.paginator.num_pages }};
	{% else %}
		var page = 1;
		var n_paginas = 1;
	{% endif %}
	
	var loadOnScroll = function() {

		if ($(window).scrollTop() > $(document).height() - ($(window).height()*1.2)) {
 			$(window).unbind();
			cargar_paginas();

		}
	};

	var cargar_paginas = function() {
		page = page + 1;
		if (page > n_paginas) {
			return false
		} else {
			$('#cargando-paginas').removeClass("pelotica-invisible").addClass("pelotica-visible");
			$.ajax({
				url: "{{ url }}?page=" + page,
				
				success: function(html)	{
					if(html){
						$("#listado").append(html);
						$('#cargando-paginas').removeClass("pelotica-visible").addClass("pelotica-invisible");
					}else{
						$('#cargando-paginas').html('<center>No hay más elementos..</center>');
					}
				},
				complete: function(data, textStatus){
					// Turn the scroll monitor back on
					$(window).bind('scroll', loadOnScroll);
				}
			});
		}
	};
				
				
$(window).bind('scroll', loadOnScroll);
						
</script>

{% endblock %}

apps/actividades/templates/actividades/contenido_usuario.html
{% load thumbnail %}
{% load i18n localeurl_tags %}

<tr><td>{% trans "Usuario" %} </td><td>

	<a href="{% url 'social-perfil' destino %}">@{{ destino }}</a>	
	({% if not perfil_destino.ocultar_nombre %}
		{{ perfil_destino.nombre }}
	{% endif %}	
	{% if not perfil_destino.ocultar_apellidos %}
		{{ perfil_destino.apellidos }}
	{% endif %}	)
	</td>
</tr>
<tr><td>{% trans "Fotos de " %}  @{{ destino }}</td><td>

		{% for i in perfil_destino.fotos_personales.all %}
			{% thumbnail i.foto "80x80" as im %}
				<img src="{{ im.url }}" alt="{{ i.foto.name }}" width="{{ im.width }}" height="{{ im.height }}"/>{% if not forloop.last %}&nbsp;{% endif %}
			{% endthumbnail %}
		{% endfor %} 
	</td>
	</tr>
<tr><td>{% trans "Grupos a los que pertenece" %} @{{ destino }}</td>
	<td>
		{% for grupo in grupos_destino %}
			{{ grupo.grupo }}{% if not forloop.last %},{% endif %}
		{% endfor %}               
	</td>
</tr>
{% if perfil_destino.provincia != '' %}
<tr><td>{% trans "Provincia " %}</td><td>{{ perfil_destino.provincia }}</td></tr>
{% endif %}
{% if not perfil_destino.ocultar_direccion and perfil_destino.direccion != '' %}
<tr><td>{% trans "Dirección " %}</td><td>{{ perfil_destino.direccion }}</td></tr>
{% endif %}

apps/actividades/templates/actividades/form_busqueda.html
{% load i18n localeurl_tags %}

<section class='row'>
	<form action="{% url 'actividad-busqueda' %}" method="POST" id="form_busqueda">
		<table class="small-11 small-centered columns">
			{% csrf_token %}
			<tr>
			<td><input id="id_busqueda" type="text" name="busqueda" maxlength="100" value="{{ datos.busqueda }}"  placeholder='{% trans "Búsqueda de actividades" %}' /></td>
				<td>{% trans "Clase" %}:</td>
				<td><select name="clase" id="id_clase">
						<option value="{{ datos.clase }}" selected="selected">{{ datos.clase }}</option>
						<option value=""></option>
						<option value="bienes">{% trans "Bienes" %}</option>
						<option value="servicios">{% trans "Servicios" %}</option>
					</select>
				</td>
				<td>{% trans "Tipo" %}:</td>
				<td><select name="tipo" id="id_tipo">
						<option value="{{ datos.tipo }}" selected="selected">{{ datos.tipo }}</option>
						<option value=""></option>
						<option value="oferta">{% trans "Oferta" %}</option>
						<option value="demanda">{% trans "Demanda" %}</option>
					</select>
				</td>
				<td>{% trans "Grupos" %}:</td>
				<td><select name="grupos" id="id_grupos">
						{% if datos.grupos %}
						<option value="{{ datos.grupos }}" selected="selected">{{ datos.grupos }}</option>
						{% else %}
						<option value="Mis grupos" selected="selected">{% trans "Mis grupos" %}</option>
						{% endif %}
						<option value="Mis grupos">{% trans "Mis grupos" %}</option>
						<option value="Todos los grupos">{% trans "Todos los grupos" %}</option>
					</select>
				</td>
				<td>{% trans "Ordenar por" %}:</td>
				<td><select name="orden" id="id_orden">
						<option value="{{ datos.orden }}" selected="selected">{{ datos.orden }}</option>
						<option value=""></option>
						<option value="clase">{% trans "clase" %}</option>
						<option value="tipo">{% trans "tipo" %}</option>
					</select>
				</td>
				<td><input type="submit" value="Buscar" class="tiny success button"/></td>
			</tr>
		</table>
	</form>
</section>

apps/actividades/templates/actividades/valoracion_concluida.html
{% load i18n localeurl_tags %}

<div>
{% trans 'Ya has terminado de valorar todo en tu comunidad' %}
</div>