apps/economia/urls.py
# coding=utf-8


# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from django.conf.urls import patterns, url
from economia.models import *
from economia.views import *


urlpatterns = patterns('economia.views',

	url(r'^index/(?P<id_cuenta>\d+)$', 'inicio', name='economia-index'),
	url(r'^intercambios_publicos/usuario/(?P<id_usuario>\d+)$', 'get_intercambios_publicos', name='economia-i-p-usuario'),
	url(r'^intercambios_publicos/grupo/(?P<id_grupo>\d+)$', 'get_intercambios_publicos', name='economia-i-p-grupo'),
	url(r'^intercambios_publicos/todos/$', 'get_intercambios_publicos', name='economia-i-p-todos'),
	url(r'^movimiento/(?P<id_movimiento>\d+)$', 'este_movimiento', name='economia-este-movimiento'),
	url(r'^actualizar_saldo/$', 'actualiza_saldo', name='economia-actualizar-saldo-ajax'),
	url(r'^recarga_actividad/$', 'recarga_actividad_ajax', name='economia-recarga-actividad-ajax'),
	url(r'^cuentas_posibles/$', 'posibles_cuentas_destino_ajax', name='economia-cuentas-posibles-ajax'),
	url(r'^pagar_paso_1/(?P<id_actividad>\d+)/(?P<id_usu>\d+)/(?P<ajax>[0-1]{1})/$','pagar_paso_1', name='economia-pagar-1'),
	url(r'^pagar_paso_2/$','pagar_paso_2', name='economia-pagar-2'),
	url(r'^resultado/(?P<ok>\d+)/(?P<id_actividad>\d+)$','confirmacion', name='economia-pagar-resultado'),

)

urls.py
#coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib.sitemaps import GenericSitemap
from actividades.models import *
from paginas.models import *
from paginas.feeds import *
from actividades.feeds import *

# añadido por las modificaciones en el django-registration
from django.contrib.auth import views as auth_views

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

actividades_dict = {
    'queryset': Idiomas_actividad.objects.all(),
    'date_field': 'creado',
}

paginas_dict = {
    'queryset': Idiomas_pagina.objects.filter(pagina__estado='publicada',pagina__visibilidad='publica'),
    'date_field': 'creado',
}

entradas_dict = {
    'queryset': Idiomas_entrada.objects.filter(entrada__estado='publicada',entrada__visibilidad='publica'),
    'date_field': 'creado',
}


sitemap = {
    'paginas': GenericSitemap(paginas_dict, priority=0.5, changefreq='weekly'),
    'entradas': GenericSitemap(entradas_dict, priority=0.5, changefreq='weekly'), 
    'actividades': GenericSitemap(actividades_dict, priority=0.5, changefreq='weekly'), 
}

urlpatterns = patterns('',


	########## PERSONALIZACION DE LA ADMINISTRACIÓN ###########
	########## ACTIVIDADES #########
	url(r'^admin/recarga_miembros_actividad/$', 'actividades.admin_views.recarga_actividad', name='admin-recarga-actividad'),
	########## GRUPO #########
	url(r'^admin/recarga_miembros_grupo/$', 'grupos.admin_views.grupos_miembros_dependientes', name='admin-grupos-recarga-miembros-grupo'),
	
	########## PAGINAS #########
	url(r'^admin/recarga_entrada/$', 'paginas.admin_views.recarga_entrada', name='admin-entrada-recarga'),
	url(r'^admin/recarga_pagina/$', 'paginas.admin_views.recarga_pagina', name='admin-pagina-recarga'),

	########## ECONOMIA #########
	url(r'^admin/recarga_form_cuenta/$', 'economia.admin_views.eco_cuenta_codas_dependientes', name='admin-eco-recarga-form-cuenta'),
	url(r'^admin/recarga_form_intercambio_1/$', 'economia.admin_views.eco_cosas_dependientes_1', name='admin-eco-recarga-form-intercambio-1'),
	url(r'^admin/recarga_form_intercambio_2/$', 'economia.admin_views.eco_cosas_dependientes_2', name='admin-eco-recarga-form-intercambio-2'),
	url(r'^admin/recarga_form_intercambio_3/$', 'economia.admin_views.eco_cosas_dependientes_3', name='admin-eco-recarga-form-intercambio-3'),
	url(r'^admin/recarga_form_intercambio_4/$', 'economia.admin_views.eco_cosas_dependientes_4', name='admin-eco-recarga-form-intercambio-4'),
	
	url(r'^admin/', include(admin.site.urls)),

	########## INTERNALIZACION ###################################
	(r'^trans/', include('datatrans.urls')), #django-datatrans
	(r'^i18n/', include('django.conf.urls.i18n')),
	url(r'^rosetta/', include('rosetta.urls')),
	(r'^set_lang/(?P<lang>\w{2})/$','utilidades.views.set_lang'),

	########## PORTADA ###################################
	url(r'^$', 'portada.views.portada', name = "portada"),
	url(r'', include('portada.urls')),

	########## ACTIVIDADES ###################################
	(r'^actividad/', include('actividades.urls')),

	########## ECONOMIA ###################################
	(r'^economia/', include('economia.urls')),
	
	########## USUARIOS ###################################
	(r'^usuarios/', include('usuarios.urls')),
	
	########## DJANGO-ALLAUTH ###################################
	(r'^accounts/', include('allauth.urls')),
	
	########## Python Social Auth ###################################
	#url('', include('social.apps.django_app.urls', namespace='social')),
	#url('', include('django.contrib.auth.urls', namespace='auth')),
	
	########### LOGIN ###################################
	#url(r'^accounts/login/$', 'django.contrib.auth.views.login', name = "login"),
	#url(r'^accounts/logout/$', 'django.contrib.auth.views.logout', kwargs=dict(next_page='/') , name = "logout"),
	#(r'^accounts/', include('registration.backends.default.urls')),

	########## twitter ###################################
	(r'^twitter/', include('twitter.urls')),

	########## GRUPOS ###################################
	(r'^grupos/', include('grupos.urls')),
	
	########## PAGINAS ###################################
	
	(r'^p/', include('paginas.urls')),
	
	########## PAGINAS ###################################
	
	(r'^ces/', include('ces.urls')),
	
	########## TINYMCE ###################################
	
	(r'^tinymce/', include('tinymce.urls')),
	
	########## SITEMAPS ###################################

	url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemap}),
	
	########## RSS ###################################
	
	url(r'^rss/entradas/$', Entradas_Generales_Feed(), name="rss-entradas-general"),
	url(r'^rss/entradas/(?P<simbolo>([^/]+))/$', Entradas_Grupo_Feed(), name="rss-entradas-grupo"),
	url(r'^rss/actividades/$', Actividades_Generales_Feed(), name="rss-actividades-general"),
	url(r'^rss/actividades/(?P<simbolo>([^/]+))/$', Actividades_Grupo_Feed(), name="rss-actividades-grupo"),
	
	########## CONFIGURACION ###################################
	

	(r'^%s/(?P<path>.*)$' % settings.MEDIA_URL[1:-1], 'django.views.static.serve',
	{'document_root': settings.MEDIA_ROOT}),
	
	# añadido por las modificaciones en el django-registration
	#override the default urls
	#url(r'^password/change/$',
				#auth_views.password_change,
				#name='password_change'),
	#url(r'^password/change/done/$',
				#auth_views.password_change_done,
				#name='password_change_done'),
	#url(r'^password/reset/$',
				#auth_views.password_reset,
				#name='password_reset'),
	#url(r'^password/reset/done/$',
				#auth_views.password_reset_done,
				#name='password_reset_done'),
	#url(r'^password/reset/complete/$',
				#auth_views.password_reset_complete,
				#name='password_reset_complete'),
	#url(r'^password/reset/confirm/(?P<uidb64>[0-9A-Za-z]+)-(?P<token>.+)/$',
				#auth_views.password_reset_confirm,
				#name='password_reset_confirm'),

	##and now add the registration urls
	#url(r'', include('registration.backends.default.urls')),
)

#if 'rosetta' in settings.INSTALLED_APPS:
	#urlpatterns += patterns('',
		#url(r'^rosetta/', include('rosetta.urls')),
	#)

	
if settings.DEBUG:
	#urlpatterns += staticfiles_urlpatterns()
	urlpatterns += patterns('',
		#(r'^' + settings.STATIC_URL.lstrip('/'), include('appmedia.urls')),
		url(r'static/(?P<path>.*)$', 'django.views.static.serve', {
		'document_root': settings.STATIC_ROOT,
	}),
)
			

apps/economia/models.py
# coding=utf-8

# Copyright (C) 2014 by Víctor Romero Blanco <info at playcircular dot com>.
# http://playcircular.com/
# It's licensed under the AFFERO GENERAL PUBLIC LICENSE unless stated otherwise.
# You can get copies of the licenses here: http://www.affero.org/oagpl.html
# AFFERO GENERAL PUBLIC LICENSE is also included in the file called "LICENSE".

from os import path
from django.conf import settings
from django.db import models
from django.contrib.auth.models import User
from django.db.models import Q
from django.utils.translation import ugettext as _
from django.template.defaultfilters import slugify
from datetime import datetime, date, time
from usuarios.models import *
from actividades.models import *
from grupos.models import *
from utilidades.combox import *
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from django.db.models import Sum,Count


###################################################################################################

class Cuenta(models.Model):
	"""
	Cuenta de cada usuario por grupo al que pertenece. La cuenta se formará así: user-n$simbolo-grupo.
	"""
	grupo = models.ForeignKey(Grupo, related_name='grupo_cuenta')
	titulares = models.ManyToManyField(User, related_name='titulares_cuenta')
	tipo = models.CharField(_(u"Tipo de cuenta"),max_length=120, blank=True, null=True, choices=TIPOS_CUENTA)
	cuenta = models.CharField(_(u"Cuenta"),unique=True, max_length=225)
	margen = models.ForeignKey(Margenes, related_name='margen_cuenta',blank=True, null=True)
	alias = models.CharField(_(u"Alias"),max_length=120, blank=True, null=True,
		help_text=_(u"Escribe un alias para identificarla mejor."))
	activo = models.BooleanField(_(u"Activo"), default=True)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	creado_por = models.ForeignKey(User, related_name='autor_add_cuenta',editable=False,blank=True,null=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)
	modificado_por = models.ForeignKey(User, related_name='autor_mod_cuenta',editable=False,blank=True,null=True)

	def __unicode__(self):
		return self.cuenta
	
	def saldo(self):
		titulares = self.titulares.all()
		un_titular = titulares[0]
		intercambio_qs = Intercambio.objects.filter(Q(usuarios=un_titular) & (Q(cuenta_origen=self) | Q(cuenta_destino=self)))
		intercambio_qs = intercambio_qs.aggregate(cantidad=Sum('cantidad'))
		saldo = intercambio_qs['cantidad']
		return unicode(saldo)
	saldo.allow_tags = True
	
	def operaciones(self):
		titulares = self.titulares.all()
		un_titular = titulares[0]
		intercambio_qs = Intercambio.objects.filter(Q(usuarios=un_titular) & (Q(cuenta_origen=self) | Q(cuenta_destino=self)))
		intercambio_qs = intercambio_qs.values('n_intercambio').order_by('n_intercambio').distinct().count()
		operaciones = intercambio_qs
		return unicode(operaciones)
	operaciones.allow_tags = True
	
	def ultimo_intercambio(self):
		titulares = self.titulares.all()
		un_titular = titulares[0]
		try:
			ultimo_intercambio = Intercambio.objects.filter(usuarios=un_titular).latest('creado')
		except Intercambio.DoesNotExist:
			ultimo_intercambio = None
		return unicode(ultimo_intercambio)
	ultimo_intercambio.allow_tags = True
	
	def titular(self):
		titulares = []
		for titular in self.titulares.all():
			titulares.append(titular.username)
		return unicode(join(titulares, ', '))
	titular.allow_tags = True
	
	def incidencias(self):
		n_incidencias = self.incidencia_cuenta.count()
		return unicode(n_incidencias)
	incidencias.allow_tags = True
	
	class Meta:
		ordering = ["-creado"]
		verbose_name = _(u"cuenta")
		verbose_name_plural = _(u"cuentas")
		
#############################################################################################################################

class Incidencia_Cuenta(models.Model):

	cuenta = models.ForeignKey(Cuenta, related_name='incidencia_cuenta',editable=False)
	nombre = models.CharField(_(u"Nombre"), max_length=250)
	descripcion = models.TextField()
	activo = models.BooleanField(_(u"Activo"), default=True)
	editable = models.BooleanField(_(u"Editable"), default=True,editable=False)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	creado_por = models.ForeignKey(User, related_name='autor_add_incidencia_cuenta',editable=False,blank=True,null=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)
	modificado_por = models.ForeignKey(User, related_name='autor_mod_incidencia_cuenta',editable=False,blank=True,null=True)

	class Meta:
		ordering = ["creado"]
		verbose_name = _(u'incidencia de cuenta')
		verbose_name_plural = _(u'incidencia de cuenta')

###################################################################################################
       
class Intercambio(models.Model):

	usuarios = models.ManyToManyField(User, related_name='usus_intercambio',editable=False)
	origen = models.ForeignKey(User, related_name='usu_origen')
	cuenta_origen = models.ForeignKey(Cuenta, related_name='cuenta_origen', help_text=_(u"Cuenta desde la que se pagará."))
	grupo_origen = models.ForeignKey(Grupo, related_name='grupo_origen')
	grupo_destino = models.ForeignKey(Grupo, related_name='grupo_destino')
	destino = models.ForeignKey(User, related_name='usu_destino')
	cuenta_destino = models.ForeignKey(Cuenta, related_name='cuenta_destino', help_text=_(u"Cuenta a la que llegará el pago."))
	actividad = models.ForeignKey(Actividad, related_name='actividad_asociada', blank=True, null=True)
	concepto = models.CharField(_(u"Concepto del intercambio"),max_length=120)
	cantidad = models.DecimalField(_(u"Cantidad"), max_digits=15, decimal_places=2, blank=False, null=False,
		help_text=_(u"Cantidad de horas o monedas que se intercambia."))
	descripcion = models.TextField(_(u"Descripción"),blank=True, null=True, help_text=_(u"Descripción de la operación."))
	publico = models.BooleanField(_(u"Público"), default=False, help_text=_(u"Si quieres que este intercambio sea público."))
	estado = models.CharField(_(u"Estado"),max_length=120, choices=ESTADO, default=u'Concluído')
	tipo = models.CharField(_(u"Tipo"),max_length=120, choices=TIPO_INTERCAMBIO, default=_(u'Normal'))
	n_intercambio = models.PositiveIntegerField(_(u"Op"), editable=False, blank=True, null=True, 
		help_text=_(u"Número de operación"))
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	creado_por = models.ForeignKey(User, related_name='autor_add_intercambio',editable=False,blank=True,null=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)
	modificado_por = models.ForeignKey(User, related_name='autor_mod_intercambio',editable=False,blank=True,null=True)
	content_type = models.ForeignKey(ContentType, editable=False, null=True)
	object_id = models.PositiveIntegerField(editable=False, null=True)
	content_object  = generic.GenericForeignKey('content_type', 'object_id')

	def __unicode__(self):
		return unicode(self.concepto)
		
	def modelo(self):
		modelo = self.content_type.name
		return unicode(modelo)
	modelo.allow_tags = True

	class Meta:
		ordering = ["-creado"]
		verbose_name = _(u"intercambio")
		verbose_name_plural = _(u"intercambios")
		
#############################################################################################################################

class Incidencia_Intercambio(models.Model):

	intercambio = models.ForeignKey(Intercambio, related_name='incidencia_intercambio',editable=False)
	nombre = models.CharField(_(u"Nombre"), max_length=250)
	descripcion = models.TextField()
	activo = models.BooleanField(_(u"Activo"), default=True)
	editable = models.BooleanField(_(u"Editable"), default=True,editable=False)
	creado = models.DateTimeField(_(u"Creado"),auto_now_add=True)
	creado_por = models.ForeignKey(User, related_name='autor_add_incidencia_intercambio',editable=False,blank=True,null=True)
	modificado = models.DateTimeField(_(u"Modificado"),auto_now=True)
	modificado_por = models.ForeignKey(User, related_name='autor_mod_incidencia_intercambio',editable=False,blank=True,null=True)

	class Meta:
		ordering = ["creado"]
		verbose_name = _(u'incidencia de intercambio')
		verbose_name_plural = _(u'incidencia de intercambio')
		
###################################################################################################

apps/economia/templates/economia/confirmacion.html
{% extends "base.html" %}
{% load i18n localeurl_tags %}


{% block title %} {{ situacion|upper }} {% endblock %}

{% block content %}


<section class="row">

	
	<header  class="small-12 columns">
		<h4>{{ situacion|upper }}</h4>
		</header>
		
		<article  class="small-12 columns">

			{% if ok %}
				<h5>{% trans "Ir a la página de mi contabilidad: " %}<a href="{% url 'economia-index' 0 %}">{% trans "Contabilidad" %}</a></h5>
				{% if actividad %}
					<h5>{% trans "Puedes dejar una valoración de la actividad" %}</h5>
					<div id="cargando_actividad" class="pelotica-invisible">
						<div class="row panel">
						<table class="small-12 columns" height="200"> 
							<tr><td><div align="center"><img src="{{ STATIC_URL }}imagenes/interface/loader.gif"  alt="cargando..."/></div></td></tr>
						</table>
						</div>
					</div>
					<div id="cargador_actividad">
						{% include "actividades/form_opinion.html" %}
					</div>
				{% endif %}
			{% else %}
				{% trans "La operación no se puede realizar." %}
			{% endif %}
		</article>

</section>




{% endblock %}

apps/economia/templates/economia/formulario_pago.html
{% load thumbnail %}
{% load i18n localeurl_tags %}

<form action="{{ url }}" method="POST" id="form_pago_1">
	<table class="small-12 columns">
	<tr><td colspan="2"><h4>{% trans "Formulario de pago" %}</h4></td><tr>
		{% csrf_token %}
		{% for field in form %}
			{% if field.is_hidden %}
				{{ field }}
			{% else %}
			<tr>
				<td>{{ field.label_tag }}</td>
				<td>{{ field }}	{% if field.errors %}<small class="error">{{ field.errors }}</small>{% endif %}</td>
			</tr>
			{% endif %}
		{% endfor %}
		{% if form.errors %}
			<tr><td colspan="2"><small class="error">{{ form.non_field_errors }}</small></td></tr>
		{% endif %}
	<tr>
		<td><a href="{{ url }}" class="small success button">Volver</a></td>
		<td><input type="submit" value="Realizar el pago" class="small success button"/></td>
	</tr>
			
	</table>
</form>

<script type="text/javascript">
// No funciona el document.ready por ajax
// $(document).ready(function(){


	$('#id_cuenta_origen').change(function(event){
		var valor_cuenta_origen = $('#id_cuenta_origen').val()
		var valor_actividad = $('#id_actividad').val()
		var datos_post = {id_cuenta_origen:valor_cuenta_origen,
							actividad:valor_actividad, 
							destino:{{ destino.pk }}, 
							csrfmiddlewaretoken:$("div input")[0].value}
		if (valor_cuenta_origen != ''){

		$.post("{% url 'economia-cuentas-posibles-ajax' %}", datos_post, function(data){
			var options = '<option value="" selected="selected">---------</option>';
			for (var i = 0; i < data.length; i++){
				options += '<option value="'+data[i]["pk"]+'">' +data[i]["fields"]["cuenta"] +'</option>'
			}
			$('#id_cuenta_destino').html(options)
			$("#id_cuenta_destino option:first").attr('selected', 'selected');
		}, "json");
		}
	});
			
	function actualiza_formulario() {
		var actividad = $('#id_actividad').val()
		
		$('#cargador_formulario').hide();
		$('#cargando_formulario').removeClass("pelotica-invisible").addClass("pelotica-visible");
		var url_1 = "/es/economia/pagar_paso_1/" + actividad + "/0/1/";   
		var data_1 = $('#form_pago_1').serialize();  
		$.post(url_1, data_1, function(status) { 
			$('#cargando_formulario').removeClass("pelotica-visible").addClass("pelotica-invisible");
			$('#cargador_formulario').html(status);
			$('#cargador_formulario').show();  
			$('#id_cuenta_origen option:first').attr('selected', 'selected')
			$('#id_cuenta_destino option:first').attr('selected', 'selected')
			}); 
		}
			
	$('#id_actividad').change(function(){
		var actividad = $('#id_actividad').val()

		if (actividad != ''){

			$('#cargador_actividad').hide();
			$('#cargando_actividad').removeClass("pelotica-invisible").addClass("pelotica-visible");
			var url_2 = "{% url 'economia-recarga-actividad-ajax' %}";  
			var data_2 = {actividad:actividad,csrfmiddlewaretoken:$("div input")[0].value}  
			// 		alert(data);
			$.post(url_2, data_2, function(status) {  
					$('#cargador_actividad').show();
					$('#cargando_actividad').removeClass("pelotica-visible").addClass("pelotica-invisible");
					$('#cargador_actividad').html(status); 
				});
			
		setTimeout(actualiza_formulario, 1000);	
		};
	
	});
			
// });

</script>

apps/economia/templates/economia/intercambio_p.html
{% load i18n localeurl_tags %}

	<tr>
		<td>{{ item.n_intercambio }}</td>
		<td><a href="{% url 'social-perfil' item.origen %}">@{{ item.origen }}</a></td>
		<td><a href="{% url 'social-perfil' item.destino %}">@{{ item.destino }}</a></td>
		<td>{{ item.cuenta_origen }}</td>
		<td>{{ item.cuenta_destino }}</td>
		<td>{{ item.cantidad }}</td>
		<td>{{ item.actividad }}</td>
		<td>{{ item.concepto }}</td>
		<td>{{ item.creado|date:"d/m/y H:i" }}</td>
	</tr>

apps/economia/templates/economia/mi_saldo.html
{% load i18n localeurl_tags %}

<form action="{% url 'economia-actualizar-saldo-ajax' %}" method="POST" id="mi_saldo">
{% csrf_token %}
<div id="saldo">
{% trans "Tu saldo es: " %}{{ d.saldo }} 
</div>
</form>

apps/economia/templates/economia/paginacion_contabilidad.html
{% load i18n localeurl_tags %}

{% if intercambio_qs %}
	{% for item in n_paginas.object_list %}
		{% include "economia/intercambio.html" %}
	{% endfor %}	
{% else %}
	<tr><td colspan="9">{% trans "No hay registros" %}</td></tr>
{% endif %}

apps/economia/templates/economia/pago_usuario.html
{% extends "base.html" %}
{% load thumbnail %}
{% load i18n localeurl_tags %}


{% block title %} Market | {{ situacion|upper }} {% endblock %}

{% block content %}


<section class="row">

	<div class="twelve columns" id="contendor-central">
	
		<header>
			<h4>{{ situacion|upper }}</h4>
		</header>
		
		<article>
			<table>
				<tr>
				<td colspan="2"><h5>{% trans "Pago al usuario:" %}
				<a href="{% url 'social-perfil' destino %}">@{{ destino }}</a>
				({{ dp_destino.nombre }} {{ dp_destino.apellidos }})</h5></td>
				</tr>
				<tr>
				<td colspan="2">
					{% include "economia/nuestras_cuentas.html" %}
				</td>
				</tr>
				<tr>
					<td colspan="2">&nbsp;</td>
				</tr>	
				<form action="{% url 'economia-pagar-2' %}" method="POST">
				{% csrf_token %}
			{% for field in form %}
				{% if field.is_hidden %}
					{{ field }}
				{% else %}
				<tr>
					<td>{{ field.label_tag }}</td>
					<td>{{ field }}	{% if field.errors %}<small class="error">{{ field.errors }}</small>{% endif %}</td>
				<td colspan="2">&nbsp;</td></tr>
				{% endif %}
			{% endfor %}
			{% if form.errors %}
				<tr><td colspan="2"><small class="error">{{ form.non_field_errors }}</small></td></tr>
			{% endif %}
				<tr>
					<td><a href="{% url 'economia-index' 0 %}" class="small success button">Volver</a></td>
					<td><input type="submit" value="Realizar el pago" class="small success button"/></td>
				</tr>
				</form>
				
			</table>
		</article>
	</div> <!--Fin contendor-central-->
</section>



<script type="text/javascript">

$(document).ready(function(){

	$('#id_actividad').change(function(){
		var actividad_elegida = document.getElementById("id_actividad").value;
		var valor = $("#id_actividad option:selected").html();
// 		alert(valor)
		var cadena = valor.split(' - - ');
		var nombre_actividad = cadena[0];
		var precio_social = cadena[1];
//  		alert(nombre_actividad + ' ' + precio_social)
		$('#id_concepto').val(nombre_actividad);
		$('#id_cantidad').val(precio_social);
	});
	
	$('#id_cuenta_origen').change(function(event){
// 		alert($('#id_grupo').val() + ' -- ' + $("div input")[0].value)
		var valor_cuenta_origen = $('#id_cuenta_origen').val()
// 		alert(valor_cuenta_origen)
		
		if (valor_cuenta_origen != ''){
		$.post("{% url 'economia-cuentas-posibles-ajax' %}", {id_cuenta_origen:$('#id_cuenta_origen').val(),destino:{{ destino.pk }}, csrfmiddlewaretoken:$("div input")[0].value}, function(data){
			var options = '<option value="" selected="selected">---------</option>';
			for (var i = 0; i < data.length; i++){
				options += '<option value="'+data[i]["pk"]+'">' +data[i]["fields"]["cuenta"] +'</option>'
			}
			$('#id_cuenta_destino').html(options)
			$("#id_cuenta_destino option:first").attr('selected', 'selected');
			//var debug = $(".contenidos .contenedor_conf h2");
			//$(debug).html(data[0].fields.anio)
			//$("debug").html(data);
		}, "json");
		}
	});

});

</script>

{% endblock %}